AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - Rakefile
    - config/*
    - db/migrate/*
    - db/seeds.rb
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120

